
services:
  api:
    build: .
    ports: 
     - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:prod"
  db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobboard
    volumes:
      - pgdata:/var/lib/posgresql/data
volumes:
  pgdata: